[package]
name = "cav-synth2"
version = "0.1.0"
edition = "2024"

[dependencies]
midir = "0.10.1"
rand = "0.8"
sdl3-src = { version = "*" } 
sdl3 = { version = "0.14.42", features = ["build-from-source-static", "ttf"] }
cpal = "0.16.0"
image = "0.25"
realfft = "3.5.0"
